/// <summary>
///
///  Even Fibonacci numbers
///  Problem 2
///
/// Each new term in the Fibonacci sequence is generated by adding the previous two terms.
/// By starting with 1 and 2, the first 10 terms will be:
/// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
///
/// By considering the terms in the Fibonacci sequence whose values do not exceed four million,
/// find the sum of the even-valued terms.
///
/// </summary>

namespace Problem2
{
	class Problem2
	{
		public static double SumOfEvenFib(int maxValue)
		{
			var sumOfFib = 0;
			var firstTerm = 0;
			var secondTerm = 1;
			int tempValue;

			while (sumOfFib < maxValue)
			{
				tempValue = firstTerm + secondTerm;

				if (tempValue % 2 == 0)
				{
					sumOfFib += tempValue;
				}

				firstTerm = secondTerm;
				secondTerm = tempValue;
			}

			return sumOfFib;
		}
	}
}